# Generated by Django 5.1.5 on 2025-04-28 18:32

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Порядок')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, max_length=724, null=True, upload_to='uploads/import_images/', verbose_name='Картинка (лучше в .webp)')),
                ('description', models.CharField(max_length=512, verbose_name='Краткое описание')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name=' Описание (полный)')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Скрыть')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Услуг',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order_number'],
                'indexes': [models.Index(fields=['is_hidden'], name='idx_uslugi_is_hidden'), models.Index(fields=['order_number'], name='idx_uslugi_order_number'), models.Index(fields=['is_hidden', 'order_number'], name='idx_uslugi_hidden_order')],
            },
        ),
    ]
