# Generated by Django 5.1.5 on 2025-05-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslugi',
            name='order_number',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок'),
        ),
    ]
