# Generated by Django 5.1.5 on 2025-05-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_alter_promo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
