# Generated by Django 5.1.5 on 2025-03-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_text', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statictext',
            options={'ordering': ['id'], 'verbose_name': 'Статический текст', 'verbose_name_plural': 'Статические тексты'},
        ),
    ]
