# Generated by Django 5.1.5 on 2025-03-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['order_number', 'name'], 'verbose_name': 'Социальная ссылка', 'verbose_name_plural': 'Социальные ссылки'},
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Вставьте полный код SVG сюда', null=True, verbose_name='Код SVG иконки'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='order_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Название значка (для справки)'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(max_length=724, verbose_name='URL ссылки'),
        ),
    ]
