# Generated by Django 5.1.5 on 2025-04-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0003_alter_projectsettings_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='icon_svg',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка'),
        ),
    ]
