# Generated by Django 5.1.5 on 2025-03-31 09:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0026_alter_menucatalog_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Ф.И.О')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('ip_address', models.GenericIPAddressField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type_order', models.CharField(default='', max_length=128, verbose_name='Тип')),
                ('type_client', models.CharField(default='', max_length=128, verbose_name='Клиент')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/files', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('shipped', 'Отправлено'), ('delivered', 'Доставлено'), ('paid_on_delivery', 'Оплачено при доставке'), ('paid_cash', 'Оплачено наличными'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], db_index=True, default='processing', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('on_delivery', 'При доставке'), ('cash', 'Наличными')], max_length=20, verbose_name='Способ оплаты')),
                ('paid', models.BooleanField(db_index=True, default=False, verbose_name='Оплачено')),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Оплаченная сумма')),
                ('order_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=724, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Цена за единицу')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.product')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'ordering': ('pk',),
            },
        ),
    ]
