# Generated by Django 5.1.5 on 2025-03-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, help_text='Например, реквизиты для юридических лиц', null=True, upload_to='order_files/', verbose_name='Прикрепить файл (реквизиты)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_client',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('legal_entity', 'Юридическое лицо')], default='individual', max_length=20, verbose_name='Тип клиента'),
        ),
    ]
