# Generated by Django 5.1.5 on 2025-04-01 07:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_file_alter_order_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Общая стоимость заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID транзакции'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, help_text='Например, реквизиты для юридических лиц', null=True, upload_to='uploads/files', verbose_name='Прикрепить файл (реквизиты)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_paid',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Оплаченная сумма'),
        ),
    ]
