# Generated by Django 5.1.5 on 2025-04-01 18:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_total_cost_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_distance_km',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите расстояние в км, если доставка за МКАД', null=True, verbose_name='Расстояние за МКАД (км)'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('mkad_inside', 'В пределах МКАД'), ('mkad_outside', 'За пределы МКАД'), ('russia', 'Доставка по России')], max_length=20, null=True, verbose_name='Способ доставки'),
        ),
    ]
