# Generated by Django 5.1.5 on 2025-04-02 10:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_shipping_cost_order_shipping_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Итоговая сумма заказа (сохранено)'),
        ),
    ]
