# Generated by Django 5.1.5 on 2025-04-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_remove_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='ID платежа YooKassa'),
        ),
        migrations.AddField(
            model_name='order',
            name='yookassa_payment_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Статус платежа YooKassa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online_yookassa', 'Онлайн оплаты (YooKassa)'), ('on_delivery', 'При доставке'), ('cash', 'Наличными')], max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('pending_payment', 'Ожидание онлайн-оплаты'), ('processing', 'В обработке'), ('shipped', 'Отправлено'), ('delivered', 'Доставлено'), ('paid_on_delivery', 'Оплачено при доставке'), ('paid_cash', 'Оплачено наличными'), ('payment_failed', 'Ошибка онлайн-оплаты'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID транзакции'),
        ),
    ]
