# Generated by Django 5.1.5 on 2025-04-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_yookassa_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('get_offer', 'Получить коммерческое предложение'), ('online_yookassa', 'Картой онлайн (Скидка 4%)'), ('on_delivery', 'Наличными либо картой'), ('cash', 'Безналичной оплатой')], max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('mkad_inside', 'В пределах МКАД'), ('mkad_outside', 'За пределы МКАД'), ('russia', 'по России в пункт выдачи')], max_length=20, null=True, verbose_name='Способ доставки'),
        ),
    ]
