# Generated by Django 5.1.5 on 2025-04-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_zakaz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zakaz',
            options={'ordering': ['-date'], 'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
    ]
