# Generated by Django 5.1.5 on 2025-03-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filials',
            options={'ordering': ['order_number', 'name'], 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы (Города)'},
        ),
    ]
