# Generated by Django 5.1.5 on 2025-04-27 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchchange',
            options={'verbose_name_plural': 'Таб. синонимов (замен) поиска'},
        ),
        migrations.AlterModelOptions(
            name='searchremove',
            options={'verbose_name_plural': 'Таб. исключений поиска'},
        ),
    ]
