# Generated by Django 5.1.5 on 2025-01-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucatalog',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='menucatalog',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='menucatalog',
            name='type_menu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='catalog',
        ),
        migrations.DeleteModel(
            name='TypeMenu',
        ),
        migrations.DeleteModel(
            name='MenuCatalog',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
