# Generated by Django 5.1.5 on 2025-01-23 11:57

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0004_remove_menucatalog_parent_remove_menucatalog_parents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название типа')),
                ('template', models.CharField(max_length=724, verbose_name='Название файла шаблона')),
            ],
            options={
                'verbose_name_plural': 'Тип меню',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MenuCatalog',
            fields=[
                ('order_number', models.FloatField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название пункта')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Название латинское')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание')),
                ('flag_footer', models.BooleanField(default=False, verbose_name='Отображать в подвале')),
                ('flag_main', models.BooleanField(default=False, verbose_name='Отображать на главной')),
                ('title_main', models.CharField(blank=True, max_length=512, null=True, verbose_name='Заголовок страницы')),
                ('keywords', models.TextField(blank=True, help_text='Ключевые слова для SEO продвижения (через запятую). Мета тэг - keywords', null=True, verbose_name='Ключевые слова (мета)')),
                ('keywords_description', models.TextField(blank=True, help_text='Содержимое мета тэга - description', null=True, verbose_name='Описание (мета)')),
                ('has_child', models.BooleanField(default=False, editable=False, verbose_name='Есть вложенные категории')),
                ('is_hidden_child', models.BooleanField(default=False, verbose_name='Скрыть дочерние пункты')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menucatalog', verbose_name='Родительский пункт')),
                ('parents', models.ManyToManyField(blank=True, db_table='MenuCatalog_and_parent_MenuCatalog', related_name='_id', to='menu.menucatalog', verbose_name='Добавить подкатегории')),
                ('type_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_menu', to='menu.typemenu', verbose_name='Тип меню')),
            ],
            options={
                'verbose_name_plural': 'Меню/Каталог',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=724, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=724, null=True, verbose_name='Название латинское')),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_set', to='menu.menucatalog', verbose_name='Каталог')),
            ],
            options={
                'verbose_name_plural': 'Продукт',
                'ordering': ['catalog'],
            },
        ),
    ]
