# Generated by Django 5.1.5 on 2025-01-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_product_slug_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucatalog',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название пункта'),
        ),
    ]
