# Generated by Django 5.1.5 on 2025-01-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_feedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=724, null=True),
        ),
    ]
