# Generated by Django 5.1.5 on 2025-01-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucatalog',
            name='slug',
            field=models.SlugField(blank=True, max_length=724, unique=True, verbose_name='Название латинское'),
        ),
    ]
