# Generated by Django 5.1.5 on 2025-01-30 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alter_menucatalog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucatalog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menucatalog_set', to='menu.menucatalog', verbose_name='Родительский пункт'),
        ),
    ]
