# Generated by Django 5.1.5 on 2025-02-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_feedlink_etag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Доступность'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='product',
            name='currencyId',
            field=models.CharField(max_length=10, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup',
            field=models.BooleanField(default=False, verbose_name='Самовывоз'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.BooleanField(default=False, verbose_name='Доступно в магазине'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Производитель'),
        ),
    ]
