# Generated by Django 5.1.5 on 2025-02-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_product_available_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedlink',
            name='feedlink',
            field=models.URLField(unique=True),
        ),
    ]
