# Generated by Django 5.1.5 on 2025-03-13 19:37

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_feedlink_feedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedlink',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable periodic updates for this feed.'),
        ),
        migrations.AddField(
            model_name='feedlink',
            name='schedule',
            field=models.CharField(blank=True, help_text='Crontab-style schedule (e.g., "0 3 * * *" for 3:00 AM daily).  Leave blank for no periodic updates.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
