# Generated by Django 5.1.5 on 2025-03-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_feedlink_enabled_feedlink_schedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedlink',
            options={'verbose_name_plural': 'Фид/ссылки'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/import_images/', verbose_name='Картинка (лучше в .webp)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыть'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hit',
            field=models.BooleanField(default=False, verbose_name='Показать на главной для хиты'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова (мета)'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (мета)'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_main',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='menucatalog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='menucatalog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menucatalog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_images',
            field=models.JSONField(blank=True, null=True, verbose_name='Доп. Картинки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='params',
            field=models.JSONField(blank=True, null=True, verbose_name='Параметры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
