# Generated by Django 5.1.5 on 2025-03-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_alter_feedlink_options_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=724, null=True, upload_to='uploads/import_images/', verbose_name='Картинка (лучше в .webp)'),
        ),
    ]
