# Generated by Django 5.1.5 on 2025-03-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedlink',
            name='schedule',
        ),
    ]
