# Generated by Django 5.1.5 on 2025-03-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_remove_feedlink_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucatalog',
            name='image',
            field=models.ImageField(blank=True, default='catalog.webp', null=True, upload_to='uploads/images', verbose_name='Картинка'),
        ),
    ]
