# Generated by Django 5.1.5 on 2025-03-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_alter_menucatalog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucatalog',
            name='image',
            field=models.ImageField(blank=True, default='default_image.webp', null=True, upload_to='uploads/images', verbose_name='Картинка'),
        ),
    ]
