# Generated by Django 5.1.5 on 2025-03-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_alter_menucatalog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_hit',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Показать на главной для хиты'),
        ),
    ]
