# Generated by Django 5.1.5 on 2025-03-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_alter_product_is_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucatalog',
            name='order_number',
            field=models.FloatField(blank=True, null=True, verbose_name='Порядок'),
        ),
    ]
