# Generated by Django 5.1.5 on 2025-03-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_alter_menucatalog_order_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedlink',
            options={'verbose_name': 'Фид', 'verbose_name_plural': 'Фид/ссылки'},
        ),
        migrations.AlterModelOptions(
            name='menucatalog',
            options={'ordering': ['order_number'], 'verbose_name': 'Меню/Каталог', 'verbose_name_plural': 'Меню/Каталог'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['catalog'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='typemenu',
            options={'ordering': ['id'], 'verbose_name': 'Тип меню', 'verbose_name_plural': 'Типы меню'},
        ),
    ]
