# Generated by Django 5.1.5 on 2025-04-10 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_alter_feedlink_options_alter_menucatalog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('availability_change', 'Изменения доступности')], default='availability_change', max_length=50)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('file_path', models.CharField(editable=False, max_length=512)),
                ('filename', models.CharField(editable=False, max_length=255)),
                ('product_change_count', models.PositiveIntegerField(default=0, editable=False)),
                ('unavailable_count', models.PositiveIntegerField(default=0, editable=False)),
                ('available_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Отчет о доступности',
                'verbose_name_plural': 'Отчеты о доступности',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='availability_changed_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Доступность изменена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Доступность'),
        ),
    ]
