# Generated by Django 5.1.5 on 2025-04-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_availabilityreport_product_availability_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityreport',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Отчет/Доступности', 'verbose_name_plural': 'Отчеты/Доступности'},
        ),
        migrations.AlterModelOptions(
            name='feedlink',
            options={'verbose_name': 'Ссылка на фид', 'verbose_name_plural': 'Ссылки на фиды'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['catalog', 'title'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='feedlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя проверка'),
        ),
        migrations.AlterField(
            model_name='menucatalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_hit', 'is_hidden', 'available', '-created_at'], name='idx_prod_hit_main'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['availability_changed_at'], name='idx_prod_avail_changed'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['catalog', 'available', 'availability_changed_at'], name='idx_prod_cat_avail_chng'),
        ),
    ]
