# Generated by Django 5.1.5 on 2025-04-11 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_alter_availabilityreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityreport',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Отчет о доступности', 'verbose_name_plural': 'Отчеты о доступности'},
        ),
        migrations.AddField(
            model_name='feedlink',
            name='last_run_status',
            field=models.CharField(blank=True, choices=[('success', 'Успех'), ('failure', 'Ошибка')], db_index=True, editable=False, max_length=10, null=True, verbose_name='Статус последнего запуска'),
        ),
        migrations.AlterField(
            model_name='availabilityreport',
            name='available_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Стали доступны (шт.)'),
        ),
        migrations.AlterField(
            model_name='availabilityreport',
            name='file_path',
            field=models.CharField(editable=False, max_length=512, verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='availabilityreport',
            name='filename',
            field=models.CharField(editable=False, max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='availabilityreport',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата генерации'),
        ),
        migrations.AlterField(
            model_name='availabilityreport',
            name='product_change_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Всего измененных продуктов'),
        ),
        migrations.AlterField(
            model_name='availabilityreport',
            name='report_type',
            field=models.CharField(choices=[('availability_change', 'Изменения доступности')], default='availability_change', max_length=50, verbose_name='Тип отчета'),
        ),
        migrations.AlterField(
            model_name='availabilityreport',
            name='unavailable_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Стали недоступны (шт.)'),
        ),
    ]
