# Generated by Django 5.1.5 on 2025-04-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_alter_availabilityreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_feed_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID в фиде (может меняться)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный и стабильный идентификатор товара', max_length=100, null=True, unique=True, verbose_name='Артикул (SKU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
