# Generated by Django 5.1.5 on 2025-04-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0031_product_product_feed_id_product_sku_alter_product_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='idx_product_sku'),
        ),
    ]
