# Generated by Django 5.1.5 on 2025-04-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0032_product_idx_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityreport',
            name='notified_products',
            field=models.ManyToManyField(blank=True, editable=False, related_name='availability_reports', to='menu.product'),
        ),
        migrations.AddField(
            model_name='availabilityreport',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('generated', 'Сгенерирован (файл)'), ('notified', 'Уведомление отправлено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
