# Generated by Django 5.1.5 on 2025-04-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_availabilityreport_notified_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityreport',
            name='error_message',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Сообщение об ошибке'),
        ),
    ]
