# Generated by Django 5.1.5 on 2025-04-15 12:00

import django_ckeditor_5.fields
import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0034_availabilityreport_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedlink',
            name='schedule',
            field=models.CharField(blank=True, help_text='Crontab-style schedule (e.g., "0 3 * * *" for 3:00 AM daily).  Leave blank for no periodic updates.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
