# Generated by Django 5.1.5 on 2025-04-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0035_feedlink_schedule_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedlink',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
