# Generated by Django 5.1.5 on 2025-04-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0036_alter_feedlink_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedlink',
            name='schedule',
        ),
    ]
