# Generated by Django 5.1.5 on 2025-04-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0037_remove_feedlink_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucatalog',
            name='has_cover',
            field=models.BooleanField(default=False, help_text='Активируйте, если на странице есть обложка', verbose_name='С обложкой'),
        ),
    ]
