# Generated by Django 5.1.5 on 2025-04-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0038_menucatalog_has_cover'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['catalog', 'is_hidden', '-created_at'], name='idx_prod_cat_criteria_ord'),
        ),
    ]
