# Generated by Django 5.1.5 on 2025-04-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0039_product_idx_prod_cat_criteria_ord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucatalog',
            options={'ordering': ['-order_number'], 'verbose_name': 'Меню/Каталог', 'verbose_name_plural': 'Меню/Каталог'},
        ),
        migrations.AddIndex(
            model_name='menucatalog',
            index=models.Index(fields=['parent', 'is_hidden', 'order_number', 'name'], name='idx_menucat_parent_list'),
        ),
        migrations.AddIndex(
            model_name='menucatalog',
            index=models.Index(fields=['slug'], name='idx_menucat_slug'),
        ),
        migrations.AddIndex(
            model_name='menucatalog',
            index=models.Index(condition=models.Q(('parent__isnull', True)), fields=['is_hidden', 'order_number', 'name'], name='idx_menucat_toplevel'),
        ),
    ]
