# Generated by Django 5.1.5 on 2025-04-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0040_alter_menucatalog_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='menucatalog',
            name='idx_menucat_toplevel',
        ),
        migrations.AddIndex(
            model_name='menucatalog',
            index=models.Index(fields=['is_hidden', 'order_number', 'name'], name='idx_menucat_toplevel_basic'),
        ),
    ]
