# Generated by Django 5.1.5 on 2025-04-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0041_remove_menucatalog_idx_menucat_toplevel_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='menucatalog',
            name='idx_menucat_parent_list',
        ),
        migrations.RemoveIndex(
            model_name='menucatalog',
            name='idx_menucat_toplevel_basic',
        ),
        migrations.AddIndex(
            model_name='menucatalog',
            index=models.Index(fields=['parent', 'type_menu', 'is_hidden', 'order_number', 'name'], name='idx_menucat_sim_lookup'),
        ),
        migrations.AddIndex(
            model_name='menucatalog',
            index=models.Index(fields=['type_menu', 'is_hidden', 'order_number', 'name'], name='idx_menucat_toplevel'),
        ),
    ]
