# Generated by Django 5.1.5 on 2025-04-30 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0042_remove_menucatalog_idx_menucat_parent_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название фильтра')),
                ('slug', models.SlugField(help_text='Используется в URL (латиница, цифры, дефис)', max_length=100, unique=True, verbose_name='Ключ для URL')),
                ('ed_izm', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ед. измерения')),
                ('order', models.PositiveIntegerField(default=100, help_text='Порядок отображения в списке фильтров', verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Категория фильтра',
                'verbose_name_plural': 'Категории фильтров',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ed_izm',
            field=models.CharField(blank=True, help_text='Единица измерения (напр., шт, кг, м², м³)', max_length=50, null=True, verbose_name='Ед. измерения'),
        ),
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=255, verbose_name='Значение')),
                ('slug', models.SlugField(blank=True, help_text='Генерируется автоматически, если пусто', max_length=255, verbose_name='Ключ для URL')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='menu.filtercategory', verbose_name='Категория фильтра')),
            ],
            options={
                'verbose_name': 'Значение фильтра',
                'verbose_name_plural': 'Значения фильтров',
                'ordering': ['category__order', 'category__name', 'order', 'value'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='products', to='menu.filtervalue', verbose_name='Фильтры продукта'),
        ),
        migrations.AddIndex(
            model_name='filtervalue',
            index=models.Index(fields=['category', 'slug'], name='menu_filter_categor_7bcf97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filtervalue',
            unique_together={('category', 'slug')},
        ),
    ]
