# Generated by Django 5.1.5 on 2025-05-14 06:39

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0043_filtercategory_product_ed_izm_filtervalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucatalog',
            name='image',
            field=models.ImageField(blank=True, help_text='Максимум 2MB', null=True, upload_to='uploads/images', validators=[menu.models.validate_image_size], verbose_name='Картинка'),
        ),
    ]
