# Generated by Django 5.1.5 on 2025-05-14 12:37

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0044_alter_menucatalog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_details',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Текстовый блок для дополнительной информации.', null=True, verbose_name='Дополнительно (детали)'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна производства'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_terms_override',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Если отличаются от общих условий.', null=True, verbose_name='Условия доставки (специфичные для товара)'),
        ),
        migrations.AddField(
            model_name='product',
            name='downloadable_materials_info',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Скачиваемые материалы'),
        ),
        migrations.AddField(
            model_name='product',
            name='form_of_release',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма выпуска'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Загрузите сюда, если хотите переопределить изображение из фида.', max_length=724, null=True, upload_to='uploads/images', verbose_name='Картинка (локальная)'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_override',
            field=models.CharField(blank=True, help_text="Используйте, если 'Производитель' из фида неточен", max_length=200, null=True, verbose_name='Производитель (если отличается от Vendor)'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=724, null=True, upload_to='uploads/import_images/', verbose_name='Картинка из фида'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/additional_images/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt текст (для SEO)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('is_custom_main', models.BooleanField(default=False, help_text='Если отмечено, это изображение будет показано как основное вместо изображения из фида.', verbose_name='Использовать как основное (заменяет из фида)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_product_images', to='menu.product')),
            ],
            options={
                'verbose_name': 'Доп. изображение продукта',
                'verbose_name_plural': 'Доп. изображения продуктов',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
