# Generated by Django 5.1.5 on 2025-05-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0045_product_additional_details_product_country_of_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_details',
            field=models.CharField(blank=True, help_text='Текстовый блок для дополнительной информации.', max_length=255, null=True, verbose_name='Дополнительно (детали)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_terms_override',
            field=models.CharField(blank=True, help_text='Если отличаются от общих условий.', max_length=255, null=True, verbose_name='Условия доставки (специфичные для товара)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='downloadable_materials_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Скачиваемые материалы'),
        ),
    ]
